
server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: gateway

    # trust-store: classpath:cacerts.jks
    # trust-store-password: 123456
    # trust-store-type: JKS

    # enabled-protocols: TLSv1.2
    
spring:
  cloud:
    gateway:
      httpclient:
        ssl:
          trustedX509Certificates:
          - file:/Users/donheekang/workspace/tmp/1103/demo-2way-ssl/demo-ms/ms.pem
          - file:/Users/donheekang/Downloads/reqres.cer

      routes:
      - id: r1
        uri: https://reqres.in
        predicates: 
        - Path=/users/1
        filters:
        - SetPath=/api/users/1

      - id: r2
        uri: https://ms:8443
        predicates: 
        - Path=/time
        filters:
        - SetPath=/now